version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 3000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: magno
      WORDPRESS_DB_PASSWORD: magno
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - './wordpress:/var/www/html'

  db:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '5000:3306'
    volumes:
      - './config/data:/var/lib/mysql:rw'
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=magno
      - MYSQL_PASSWORD=magno
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    links:
      - db
    ports:
      - '8080:80'

volumes:
  wordpress:
  db:
