version: '3'
services:
  php:
    build: './config/php'
    volumes:
      - './app:/app'

  db:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '5000:3306'
    volumes:
      - './config/data:/var/lib/mysql:rw'
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=magno
      - MYSQL_PASSWORD=magno
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    links:
      - db
    ports:
      - '8080:80'

  web:
    image: 'nginx:latest'
    ports:
      - '3000:80'
    volumes:
      - './app:/app'
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf